sample for Laravel - Copy/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('hello','PostController');

sample for Laravel - Copy/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

sample for Laravel - Copy/app/post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class post extends Model
{
    protected $fillable= ['title','content'];
    //
}

sample for Laravel - Copy/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

sample for Laravel - Copy/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        //
        //$posts = post::all();
        
        $posts = post::orderBy('id','desc')->paginate(5);
        return view('posts.index',['p'=>$posts]);
    }

    public function create()
    {
        return view('posts.create');
    }

    
    public function store(Request $request)
    {
        //dd($request);
       // return $request->title;
       $this->validate($request, [
            'title'=>'required|min:3',
            'content'=>'required|min:10'

    
       ]);
        //return 'dhaka';
       post::create([
           'title'=>$request->title,
           'content'=>$request->content
       ]);

       return redirect(route('hello.index'));
        
    }

    public function show($post)
    {
        //return $post;
        //dd($post);
         $posts = post::find($post);
         return view('posts.show', ['post'=> $posts]);
        //echo $post->title;
        
        //return view('posts.show', ['post'=> $posts]);
      
    }

    public function edit($post)
    {
        //
        $fetch = post::find($post);
        return view('posts.edit', compact('fetch'));
    }

    public function update(Request $request, $post)
    {
        /*$post->title = $request->title;
        $post->content = $request->content;*/
        //post::where('id',$post)->update($request-all());
        //$post->save();

        
        $p = post::find($post);
       // dd($p);
        $p->title = $request->get('title');
        $p->content = $request->get('content');
        $p->save();
        return redirect(route('hello.index'));

    }

    public function destroy($post)
    {
        $s = post::find($post);
        $s->delete();
        return redirect(route('hello.index'));
    }
}

sample for Laravel - Copy/resources/views/posts/create.blade.php
@extends('posts.master')

@section('body')
 
    <div class="card mt-2 p-2">
     <h3>Add Post</h3>
     @if($errors->all())
      <div class="alert alert-danger"> 
      @foreach($errors->all() as $error)
      <li>{{$error}}</li>
      @endforeach
      
      
      </div>

     @endif
     
        <form action ="{{route('hello.store')}}" , method ="post">
        @csrf
          <div class="form-group">
            <label for="comment">title</label>
            <input type="text" class="form-control"  name = "title">
            <label for="comment">content</label>
            <textarea class="form-control" rows="5" name = "content"></textarea>
            <button type = "submit" class="btn btn-outline-primary mt-2">Add</button>
          </div>
        </form>
    </div>
  @endsection

sample for Laravel - Copy/resources/views/posts/edit.blade.php
@extends('posts.master')

@section('body')
 
    <div class="card mt-2 p-2">
     <h3>Add Post</h3>
     @if($errors->all())
      <div class="alert alert-danger"> 
      @foreach($errors->all() as $error)
      <li>{{$error}}</li>
      @endforeach
      
      
      </div>

     @endif
     
        <form action ="{{route('hello.update',$fetch->id)}}" , method ="post">
        @csrf
        @method('put')
          <div class="form-group">
            <label for="comment">title</label>
            <input type="text" class="form-control"  name = "title" value = "{{$fetch->title}}">
            <label for="comment">content</label>
            <textarea class="form-control" rows="5" name = "content">{{$fetch->content}}</textarea>
            <button type = "submit" class="btn btn-outline-primary mt-2">Update</button>
          </div>
        </form>
    </div>
  @endsection

sample for Laravel - Copy/resources/views/posts/index.blade.php
@extends('posts.master')

@section('body')
  @foreach($p as $post)
    <div class="card mt-2 p-2">
     <div class="card-body">
     <a href = "{{route('hello.show', $post->id)}}">{{$post->title}}</a>
    <a href ="{{route('hello.edit', $post->id)}}" class="btn btn-info ml-2">Edit</a>
    <form onsubmit = "return confirm('are you sure you want to delete this post?')" action = "{{route('hello.destroy', $post->id)}}" method ="post" class = "d-inline-block">
    @csrf
    {{method_field('delete')}}
    <button type = "submit" class="btn btn-danger">Delete</button>
    </form>
     </div>
    
    </div>
  @endforeach

  <div class="mt-3">
  {{$p->links()}}</div>
@endsection

sample for Laravel - Copy/resources/views/posts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href = "/css/bootstrap.css">
    <title>Document</title>
</head>
<body>
    
    <div class="container">
      <center><h1 class="mt-5">POST<h1></center>
      <div class="big-info">
    <button class="btn btn-warning"><a href = "{{route('hello.index')}}">Home</a></button>
    <button class="btn btn-warning"> <a href = "{{route('hello.create')}}">Create</a></button>

    
    </div>
      @yield('body')
      
    </div>
    
</body>
</html>

sample for Laravel - Copy/resources/views/posts/show.blade.php
@extends('posts.master')

@section('body')
 
    <div class="card-header mt-2">
      <h2>{{$post->title}}</h2>
    </div>
    
    <div class="card-body">
    <h2>{{$post->content}}</h2>
    
    </div>
@endsection